src/Entity/Computer.php
<?php

namespace App\Entity;

use App\Repository\ComputerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComputerRepository::class)]
class Computer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $annee_sortie = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_serie = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $marque = null;

    #[ORM\ManyToOne(inversedBy: 'computers')]
    private ?user $auteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getAnneeSortie(): ?int
    {
        return $this->annee_sortie;
    }

    public function setAnneeSortie(int $annee_sortie): self
    {
        $this->annee_sortie = $annee_sortie;

        return $this;
    }

    // public function getNumeroSerie(): ?string
    // {
    //     return $this->numero_serie;
    // }

    // public function setNumeroSerie(string $numero_serie): self
    // {
    //     $this->numero_serie = $numero_serie;

    //     return $this;
    // }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getMarque(): ?Brand
    {
        return $this->marque;
    }

    public function setMarque(?Brand $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getAuteur(): ?user
    {
        return $this->auteur;
    }

    public function setAuteur(?user $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }
}

src/Form/ComputerType.php
<?php

namespace App\Form;

use App\Entity\Computer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ComputerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('modele')
            ->add('description')
            ->add('prix')
            ->add('annee_sortie')
            ->add('numero_serie')
            ->add('image')
            ->add('marque')
            ->add('auteur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Computer::class,
        ]);
    }
}

src/Controller/ComputerController.php
<?php

namespace App\Controller;

use App\Entity\Computer;
use App\Form\ComputerType;
use App\Repository\ComputerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/computer')]
class ComputerController extends AbstractController
{
    #[Route('/', name: 'app_computer_index', methods: ['GET'])]
    public function index(ComputerRepository $computerRepository): Response
    {
        return $this->render('computer/index.html.twig', [
            'computers' => $computerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_computer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ComputerRepository $computerRepository): Response
    {
        $computer = new Computer();
        $form = $this->createForm(ComputerType::class, $computer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $computerRepository->save($computer, true);

            return $this->redirectToRoute('app_computer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('computer/new.html.twig', [
            'computer' => $computer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_computer_show', methods: ['GET'])]
    public function show(Computer $computer): Response
    {
        return $this->render('computer/show.html.twig', [
            'computer' => $computer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_computer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Computer $computer, ComputerRepository $computerRepository): Response
    {
        $form = $this->createForm(ComputerType::class, $computer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $computerRepository->save($computer, true);

            return $this->redirectToRoute('app_computer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('computer/edit.html.twig', [
            'computer' => $computer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_computer_delete', methods: ['POST'])]
    public function delete(Request $request, Computer $computer, ComputerRepository $computerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$computer->getId(), $request->request->get('_token'))) {
            $computerRepository->remove($computer, true);
        }

        return $this->redirectToRoute('app_computer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/computer/_delete_form.html.twig
<form method="post" action="{{ path('app_computer_delete', {'id': computer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ computer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/computer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/computer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Computer{% endblock %}

{% block body %}
    <h1>Edit Computer</h1>

    {{ include('computer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_computer_index') }}">back to list</a>

    {{ include('computer/_delete_form.html.twig') }}
{% endblock %}

templates/computer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Computer index{% endblock %}

{% block body %}
    <h1>Computer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Modele</th>
                <th>Description</th>
                <th>Prix</th>
                <th>Annee_sortie</th>
                <th>Numero_serie</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for computer in computers %}
            <tr>
                <td>{{ computer.id }}</td>
                <td>{{ computer.modele }}</td>
                <td>{{ computer.description }}</td>
                <td>{{ computer.prix }}</td>
                <td>{{ computer.anneeSortie }}</td>
                <td>{{ computer.numeroSerie }}</td>
                <td>{{ computer.image }}</td>
                <td>
                    <a href="{{ path('app_computer_show', {'id': computer.id}) }}">show</a>
                    <a href="{{ path('app_computer_edit', {'id': computer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_computer_new') }}">Create new</a>
{% endblock %}

templates/computer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Computer{% endblock %}

{% block body %}
    <h1>Create new Computer</h1>

    {{ include('computer/_form.html.twig') }}

    <a href="{{ path('app_computer_index') }}">back to list</a>
{% endblock %}

templates/computer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Computer{% endblock %}

{% block body %}
    <h1>Computer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ computer.id }}</td>
            </tr>
            <tr>
                <th>Modele</th>
                <td>{{ computer.modele }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ computer.description }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ computer.prix }}</td>
            </tr>
            <tr>
                <th>Annee_sortie</th>
                <td>{{ computer.anneeSortie }}</td>
            </tr>
            <tr>
                <th>Numero_serie</th>
                <td>{{ computer.numeroSerie }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ computer.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_computer_index') }}">back to list</a>

    <a href="{{ path('app_computer_edit', {'id': computer.id}) }}">edit</a>

    {{ include('computer/_delete_form.html.twig') }}
{% endblock %}